# Generated by Django 2.0.5 on 2018-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoscowPythonMeetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_number', models.IntegerField(verbose_name='Номер митапа')),
                ('meetup_day', models.IntegerField(verbose_name='День Митапа')),
                ('meetup_month', models.TextField(choices=[('Января', 'ЯНВ'), ('Февраля', 'ФЕВ'), ('Марта', 'МАР'), ('Апреля', 'АПР'), ('Мая', 'МАЙ'), ('Июня', 'ИЮН'), ('Июля', 'ИЮЛ'), ('Августа', 'АВГ'), ('Сентября', 'СЕН'), ('Октября', 'ОКТ'), ('Ноября', 'НОВ'), ('Декабря', 'ДЕК')], default='Январь', verbose_name='Месяц Митапа')),
                ('meetup_time', models.TimeField(auto_now=True, verbose_name='Время Митапа')),
                ('meetup_link', models.URLField(default='http://www.moscowpython.ru')),
            ],
        ),
    ]
