# Generated by Django 2.0.5 on 2018-05-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moscowpythonmeetup',
            options={'verbose_name_plural': 'MoscowPython Meetups'},
        ),
    ]
