# Generated by Django 2.0.5 on 2018-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20180526_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moscowpythonmeetup',
            name='meetup_month',
            field=models.TextField(choices=[('Января', 'ЯНВАРЬ'), ('Февраля', 'ФЕВ'), ('Марта', 'МАР'), ('Апреля', 'АПР'), ('Мая', 'МАЙ'), ('Июня', 'ИЮН'), ('Июля', 'ИЮЛ'), ('Августа', 'АВГ'), ('Сентября', 'СЕН'), ('Октября', 'ОКТ'), ('Ноября', 'НОВ'), ('Декабря', 'ДЕК')], default='Январь', verbose_name='Месяц Митапа'),
        ),
    ]
