# Generated by Django 2.0.6 on 2018-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_moscowpythonmeetup_meetup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_2',
            field=models.DateField(blank=True, default=None, help_text='Дата второго занятия', null=True, verbose_name='Второй день занятий'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_3',
            field=models.DateField(blank=True, default=None, help_text='Дата третьего занятия', null=True, verbose_name='Третий день занятий'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_4',
            field=models.DateField(blank=True, default=None, help_text='Дата четвертого занятия', null=True, verbose_name='Четвертый день занятий'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_5',
            field=models.DateField(blank=True, default=None, help_text='Дата пятого занятия', null=True, verbose_name='Пятый день занятий'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_6',
            field=models.DateField(blank=True, default=None, help_text='Дата шестого занятия', null=True, verbose_name='Шестой день занятий'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_7',
            field=models.DateField(blank=True, default=None, help_text='Дата седьмого занятия', null=True, verbose_name='Седьмой день занятий'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_8',
            field=models.DateField(blank=True, default=None, help_text='Дата восьмого занятия', null=True, verbose_name='Восьмой день занятий'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='course_day_9',
            field=models.DateField(blank=True, default=None, help_text='Дата девятого занятия', null=True, verbose_name='Девятый день занятий'),
        ),
        migrations.AlterField(
            model_name='graduateprojects',
            name='project_image',
            field=models.ImageField(default=None, help_text='Пример интерфейса проекта', upload_to='projects/'),
        ),
    ]
