# Generated by Django 2.0.5 on 2018-05-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20180526_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moscowpythonmeetup',
            name='meetup_month',
            field=models.TextField(choices=[('Января', 'Январь'), ('Февраля', 'Февраль'), ('Марта', 'Март'), ('Апреля', 'Апрель'), ('Мая', 'Май'), ('Июня', 'Июнь'), ('Июля', 'Июль'), ('Августа', 'Август'), ('Сентября', 'Сентябрь'), ('Октября', 'Октябрь'), ('Ноября', 'Ноябрь'), ('Декабря', 'Декабрь')], default='Январь', verbose_name='Месяц Митапа'),
        ),
    ]
