# Generated by Django 2.0.6 on 2018-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20180609_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_title',
            field=models.CharField(default=None, help_text='Большие буквы заголовка', max_length=140, verbose_name='Заголовок отзыва'),
        ),
    ]
