# Generated by Django 2.0.6 on 2018-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_feedback_feedback_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author_photo',
            field=models.ImageField(help_text='Прикрепите фото автора отзыва', null=True, upload_to='feedbacks/', verbose_name='Фотография автора'),
        ),
    ]
