# Generated by Django 2.0.5 on 2018-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20180526_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPythonCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_index', models.IntegerField(verbose_name='Набор №')),
                ('course_start_date', models.DateField(verbose_name='Дата начала курса')),
                ('course_end_date', models.DateField(verbose_name='Дата окончания курса')),
                ('online_gepard_price', models.IntegerField(verbose_name='Цена "Гепард" (Онлайн)')),
                ('online_gepard_due_date', models.DateField(verbose_name='"Гепард" (Онлайн) действительна до')),
                ('online_mustang_price', models.IntegerField(verbose_name='Цена "Мустанг" (Онлайн)')),
                ('online_mustang_due_date', models.DateField(verbose_name='"Мустанг" (Онлайн) действительна до')),
                ('online_panda_price', models.IntegerField(verbose_name='Цена "Панда" (Онлайн)')),
                ('online_panda_due_date', models.DateField(verbose_name='"Панда" (Онлайн) действительна до')),
            ],
            options={
                'verbose_name_plural': 'LearnPython Наборы',
            },
        ),
    ]
