# Generated by Django 2.0.6 on 2018-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20180609_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author_photo',
            field=models.ImageField(blank=True, help_text='Прикрепите фото автора отзыва', upload_to='feedbacks/', verbose_name='Фотография автора'),
        ),
    ]
