# Generated by Django 2.0.5 on 2018-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20180526_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'LearnPython Отзывы',
            },
        ),
        migrations.AddField(
            model_name='courators',
            name='courator_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courators',
            name='courator_social_network',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='courators',
            name='courator_status',
            field=models.BooleanField(default=True, verbose_name='Куратор для ближайшего набора?'),
        ),
    ]
