# Generated by Django 2.0.5 on 2018-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20180526_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'LearnPython Проекты учеников',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_author',
            field=models.CharField(max_length=50, null=True, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_author_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_author_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_author_position',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность выпускника'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='courator_github',
            field=models.URLField(blank=True),
        ),
    ]
