# Generated by Django 2.0.6 on 2018-06-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20180526_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на автора'),
        ),
    ]
