# Generated by Django 2.0.5 on 2018-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20180602_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_author', models.CharField(help_text='Как зовут автора истории?', max_length=50, null=True, verbose_name='Автор истории')),
                ('story_author_photo', models.ImageField(help_text='Прикрепите фото автора истории', null=True, upload_to='', verbose_name='Фотография автора')),
                ('story_author_position', models.CharField(help_text='Кто теперь выпускник', max_length=50, null=True, verbose_name='Должность выпускника')),
                ('story_author_background', models.TextField(help_text='Прим. "В прошлом: терапевт"', verbose_name='В прошлом автор был:')),
            ],
            options={
                'verbose_name_plural': 'Learn Python Истории учеников',
            },
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='end_registration_date',
            field=models.DateTimeField(default=None, help_text='Во сколько закрывается регистрация?', verbose_name='Дата закрытия регистрации'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author_photo',
            field=models.ImageField(help_text='Прикрепите фото автора отзыва', null=True, upload_to='', verbose_name='Фотография автора'),
        ),
    ]
