# Generated by Django 2.0.5 on 2018-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20180602_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author',
            field=models.CharField(help_text='Кто автор отзыва?', max_length=50, null=True, verbose_name='Автор отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author_link',
            field=models.URLField(blank=True, help_text='Есть ли ссылка на соцсеточки автора?', null=True, verbose_name='Ссылка на автора'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author_position',
            field=models.CharField(help_text='Кем работает автор?', max_length=50, null=True, verbose_name='Должность выпускника'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(help_text='А сюда пишем отзыв автора', null=True, verbose_name='Текст отзыва'),
        ),
    ]
