# Generated by Django 2.0.5 on 2018-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20180602_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moscowpythonmeetup',
            name='meetup_link',
            field=models.URLField(default='http://www.moscowpython.ru', verbose_name='Ссылка на митап'),
        ),
    ]
