# Generated by Django 2.0.5 on 2018-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20180602_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduateprojects',
            options={'verbose_name_plural': 'LearnPython Проекты Учеников'},
        ),
        migrations.AlterField(
            model_name='moscowpythonmeetup',
            name='meetup_link',
            field=models.URLField(default='http://www.moscowpython.ru', help_text='Ссылка по стандарту, можно менять', verbose_name='Ссылка на митап'),
        ),
    ]
