# Generated by Django 2.0.5 on 2018-06-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20180609_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduatestories',
            name='story_text',
        ),
        migrations.AddField(
            model_name='graduatestories',
            name='story_text_after_course',
            field=models.TextField(default=None, help_text='После курса', verbose_name='История пользователя'),
        ),
        migrations.AddField(
            model_name='graduatestories',
            name='story_text_before_course',
            field=models.TextField(default=None, help_text='До курса', verbose_name='История пользователя'),
        ),
        migrations.AddField(
            model_name='graduatestories',
            name='story_text_on_course',
            field=models.TextField(default=None, help_text='На курсе', verbose_name='История пользователя'),
        ),
    ]
