# Generated by Django 2.0.5 on 2018-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20180602_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatestories',
            name='story_text',
            field=models.TextField(default=None, help_text='Что хотел бы автор рассказать', verbose_name='История пользователя'),
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_author_background',
            field=models.CharField(help_text='Прим. "В прошлом: терапевт"', max_length=150, verbose_name='В прошлом автор был:'),
        ),
    ]
