# Generated by Django 2.0.5 on 2018-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20180602_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprojects',
            name='project_image',
            field=models.ImageField(default=None, help_text='Пример интерфейса проекта', upload_to=''),
        ),
        migrations.AddField(
            model_name='graduateprojects',
            name='project_name',
            field=models.CharField(default=None, help_text='Название проекта', max_length=150),
        ),
    ]
