# Generated by Django 2.0.5 on 2018-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_graduatestories_story_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatestories',
            name='story_author_photo',
            field=models.ImageField(help_text='Прикрепите фото автора истории', null=True, upload_to='stories/', verbose_name='Фотография автора'),
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Никогда не программировал', 'Никогда не программировал')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
