# Generated by Django 2.0.5 on 2018-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_auto_20180602_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPythonCoursePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.IntegerField(default=None, help_text='Мустанг / Гепард / Панда и вот это все', verbose_name='Название временного отрезка')),
                ('course_type', models.TextField(choices=[('Online', 'Online'), ('Offline', 'Offline')], help_text='Выберите тип курса', verbose_name='Тип курса')),
                ('price_range_end_date', models.DateField(help_text='Когда истекает данное предложение', verbose_name='Дата окончания интервала')),
                ('price_range_price', models.IntegerField(help_text='Сколько стоит курс в этот период', verbose_name='Цена')),
            ],
            options={
                'verbose_name_plural': 'LearnPython Цены на курсы',
            },
        ),
        migrations.RemoveField(
            model_name='learnpythoncourse',
            name='online_gepard_due_date',
        ),
        migrations.RemoveField(
            model_name='learnpythoncourse',
            name='online_gepard_price',
        ),
        migrations.RemoveField(
            model_name='learnpythoncourse',
            name='online_mustang_due_date',
        ),
        migrations.RemoveField(
            model_name='learnpythoncourse',
            name='online_mustang_price',
        ),
        migrations.RemoveField(
            model_name='learnpythoncourse',
            name='online_panda_due_date',
        ),
        migrations.RemoveField(
            model_name='learnpythoncourse',
            name='online_panda_price',
        ),
    ]
