# Generated by Django 2.0.5 on 2018-06-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_auto_20180602_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courators',
            name='courator_github',
            field=models.URLField(blank=True, help_text='Ссылка на гит-хаб куратора'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='courator_social_network',
            field=models.URLField(blank=True, help_text='Если есть, ссылка на соцсеточку'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='courator_status',
            field=models.BooleanField(default=True, help_text='Куратор работает в текущем наборе?', verbose_name='Куратор для ближайшего набора?'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='curator_bio',
            field=models.TextField(help_text='Где и кем работает, что программирует', verbose_name='Биография куратора'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='curator_motto',
            field=models.CharField(help_text='Через тернии к звездам или что-нибудь такое', max_length=150, verbose_name='Девиз куратора'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='curator_name',
            field=models.CharField(help_text='Сначало имя, потом фамилия', max_length=50, verbose_name='Имя и фамилия куратора'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='curator_photo',
            field=models.ImageField(help_text='Фотография куратора', upload_to=''),
        ),
    ]
