# Generated by Django 2.0.5 on 2018-06-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_auto_20180604_0840'),
        ('mainpage', '0009_auto_20180607_1040'),
    ]

    operations = [
    ]
