# Generated by Django 2.0.5 on 2018-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_auto_20180610_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moscowpythonmeetup',
            name='meetup_month',
        ),
        migrations.RemoveField(
            model_name='moscowpythonmeetup',
            name='meetup_time',
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Никогда не программировал', 'Никогда не программировал'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Хочу новый навык или работу', 'Хочу новый навык или работу')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
        migrations.AlterField(
            model_name='moscowpythonmeetup',
            name='meetup_day',
            field=models.DateTimeField(help_text='Где и во сколько?', verbose_name='Дата и время митапа'),
        ),
    ]
