# Generated by Django 2.0.5 on 2018-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_merge_20180607_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courators',
            name='courator_github',
            field=models.URLField(blank=True, help_text='Ссылка на гит-хаб куратора', verbose_name='GitHub куратора'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='courator_social_network',
            field=models.URLField(blank=True, help_text='Если есть, ссылка на соцсеточку', verbose_name='Соцсеточка куратора'),
        ),
        migrations.AlterField(
            model_name='courators',
            name='curator_photo',
            field=models.ImageField(help_text='Фотография куратора', upload_to='', verbose_name='Фото куратора'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_author_link',
            field=models.URLField(blank=True, help_text='Есть ли ссылка на соцсеточки автора?', null=True, verbose_name='Ссылка на автора'),
        ),
    ]
