# Generated by Django 2.0.5 on 2018-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_auto_20180908_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpythoncourse',
            name='online_session_closed',
            field=models.BooleanField(default=False, help_text='Поставь галочку, чтобы закрыть набор', verbose_name='Закрыть онлайн набор?'),
        ),
    ]
