# Generated by Django 2.0.5 on 2018-06-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_remove_moscowpythonmeetup_meetup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='moscowpythonmeetup',
            name='meetup_time',
            field=models.TimeField(auto_now=True, help_text='Время начала митапа', verbose_name='Время Митапа'),
        ),
    ]
