# Generated by Django 2.0.5 on 2018-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_learnpythoncourse_online_session_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpythoncourse',
            name='time_lessons_ends',
            field=models.TimeField(blank=True, default='14:00:00', help_text='Во сколько занятие заканчивается', null=True, verbose_name='Время окончания занятия'),
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='time_lessons_start',
            field=models.TimeField(blank=True, default='11:00:00', help_text='Во сколько занятие начинается', null=True, verbose_name='Время начала занятия'),
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Никогда не программировал', 'Никогда не программировал'), ('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
