# Generated by Django 2.0.5 on 2018-11-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_auto_20181121_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnpythoncourse',
            old_name='offline_session_closed',
            new_name='offline_session_end',
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Никогда не программировал', 'Никогда не программировал'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
