# Generated by Django 2.0.5 on 2018-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_auto_20181122_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnpythoncourse',
            old_name='time_lessons_ends',
            new_name='offline_time_lessons_ends',
        ),
        migrations.RenameField(
            model_name='learnpythoncourse',
            old_name='time_lessons_start',
            new_name='offline_time_lessons_start',
        ),
        migrations.AddField(
            model_name='learnpythoncourse',
            name='online_time_of_call',
            field=models.TimeField(blank=True, default='11:30:00', help_text='Во сколько созваниваемся?', null=True, verbose_name='Время начала звонка'),
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Никогда не программировал', 'Никогда не программировал'), ('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
