# Generated by Django 2.0.5 on 2019-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_auto_20181124_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateProjectsVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=None, help_text='Название проекта', max_length=150)),
                ('project_url', models.CharField(default=None, help_text='Ссылка на Youtube', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'LearnPython Видео проектов Учеников',
            },
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Никогда не программировал', 'Никогда не программировал'), ('Хочу новый навык или работу', 'Хочу новый навык или работу')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
