# Generated by Django 2.0.5 on 2019-04-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0025_auto_20190421_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprojectsvideos',
            name='project_course',
            field=models.CharField(default=None, help_text='Номер Выпуска', max_length=5),
        ),
        migrations.AddField(
            model_name='graduateprojectsvideos',
            name='project_description',
            field=models.TextField(default=None, help_text='Краткое описание проекта', verbose_name='Описание проект'),
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Никогда не программировал', 'Никогда не программировал'), ('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
