# Generated by Django 2.1.5 on 2019-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0026_auto_20190421_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateprojects',
            name='project_image',
            field=models.ImageField(default=None, help_text='Пример интерфейса проекта', upload_to='projects/', verbose_name='Пример интерфейса'),
        ),
        migrations.AlterField(
            model_name='graduateprojects',
            name='project_name',
            field=models.CharField(default=None, help_text='Название проекта', max_length=150, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='graduateprojectsvideos',
            name='project_course',
            field=models.CharField(default=None, help_text='Номер Выпуска', max_length=5, verbose_name='Номер набора'),
        ),
        migrations.AlterField(
            model_name='graduateprojectsvideos',
            name='project_name',
            field=models.CharField(default=None, help_text='Название проекта', max_length=150, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='graduateprojectsvideos',
            name='project_url',
            field=models.CharField(default=None, help_text='Ссылка на Youtube', max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Никогда не программировал', 'Никогда не программировал'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
