# Generated by Django 2.1.5 on 2019-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0027_auto_20190505_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpythoncourse',
            name='timepad_event_id',
            field=models.TextField(help_text='/dashboard/event/909971 <- вот этот', null=True, verbose_name='Номер евента в Timepad'),
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Никогда не программировал', 'Никогда не программировал'), ('Хочу новый навык или работу', 'Хочу новый навык или работу')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
