# Generated by Django 2.1.5 on 2019-05-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0028_auto_20190507_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnpythoncourse',
            name='timepad_event_id',
            field=models.CharField(help_text='/dashboard/event/909971 <- вот этот', max_length=20, null=True, verbose_name='Номер эвента в Timepad'),
        ),
    ]
