# Generated by Django 2.1.5 on 2019-08-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0031_auto_20190507_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_name', models.CharField(default=None, help_text='Название подкаста', max_length=150, verbose_name='Название подкаста')),
                ('podcast_url', models.CharField(default=None, help_text='Ссылка на Youtube', max_length=250, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'LearnPython Подкаст с учеником',
            },
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Никогда не программировал', 'Никогда не программировал'), ('Хочу новый навык или работу', 'Хочу новый навык или работу')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
