# Generated by Django 2.1.11 on 2019-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0032_auto_20190820_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curators',
            name='curator_name',
            field=models.CharField(help_text='Сначала имя, потом фамилия', max_length=50, verbose_name='Имя и фамилия куратора'),
        ),
        migrations.AlterField(
            model_name='learnpythoncourseprices',
            name='course_type',
            field=models.TextField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('OfflinePenza', 'OfflinePenza')], help_text='Выберите тип курса', verbose_name='Тип курса'),
        ),
    ]
