# Generated by Django 2.1.11 on 2020-03-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0034_auto_20191227_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnpythoncourse',
            old_name='offline_session_end',
            new_name='offline_session_closed',
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Никогда не программировал', 'Никогда не программировал')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
