# Generated by Django 2.2.20 on 2021-08-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0036_auto_20200523_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPythonMultiCityCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(help_text='Какой город указывать в списке', max_length=50, verbose_name='Название города')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('early_date', models.DateField(verbose_name='Дата окончания ранней регистрации')),
                ('early_price', models.IntegerField(verbose_name='Стоимость курса в раннюю регистрацию')),
                ('early_installment_price', models.IntegerField(verbose_name='Стоимость рассрочки')),
                ('basic_date', models.DateField(verbose_name='Дата начала основной регистрации')),
                ('basic_price', models.IntegerField(verbose_name='Стоимость курса в обычную регистрацию')),
                ('basic_installment_price', models.IntegerField(verbose_name='Стоимость рассрочки')),
            ],
            options={
                'verbose_name_plural': 'LearnPython Цены на курсы в разных городах',
            },
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Никогда не программировал', 'Никогда не программировал')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
