# Generated by Django 2.2.20 on 2021-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0037_auto_20210803_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnpythonmulticitycourses',
            old_name='cityname',
            new_name='city_name',
        ),
        migrations.AlterField(
            model_name='graduatestories',
            name='story_section',
            field=models.TextField(choices=[('Хочу новый навык или работу', 'Хочу новый навык или работу'), ('Есть опыт, хочу освоить новый язык', 'Есть опыт, хочу освоить новый язык'), ('Никогда не программировал', 'Никогда не программировал')], default='Никогда не программировал', help_text='В какую из секций историй', verbose_name='Раздел истории'),
        ),
    ]
