# Generated by Django 4.2.4 on 2023-08-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0039_alter_graduatestories_story_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='GraduateProjectsVideos',
        ),
        migrations.DeleteModel(
            name='GraduateStories',
        ),
        migrations.DeleteModel(
            name='LearnPythonCourse',
        ),
        migrations.DeleteModel(
            name='LearnPythonCoursePrices',
        ),
        migrations.DeleteModel(
            name='LearnPythonMultiCityCourses',
        ),
        migrations.DeleteModel(
            name='MoscowPythonMeetup',
        ),
        migrations.DeleteModel(
            name='Podcasts',
        ),
        migrations.AlterModelOptions(
            name='curators',
            options={'verbose_name_plural': 'Кураторы'},
        ),
        migrations.RemoveField(
            model_name='curators',
            name='curator_github',
        ),
        migrations.RemoveField(
            model_name='curators',
            name='curator_motto',
        ),
        migrations.RemoveField(
            model_name='curators',
            name='curator_social_network',
        ),
        migrations.RemoveField(
            model_name='curators',
            name='curator_status',
        ),
        migrations.AddField(
            model_name='curators',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной'),
        ),
    ]
