# Generated by Django 4.2.4 on 2023-08-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0040_delete_feedback_delete_graduateprojectsvideos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepad_event_id', models.CharField(blank=True, max_length=64, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('end_registration_date', models.DateField()),
                ('early_price_rub', models.IntegerField()),
                ('late_price_rub', models.IntegerField()),
                ('early_price_date_to', models.DateField()),
                ('late_price_date_from', models.DateField()),
            ],
        ),
    ]
