# Generated by Django 4.2.4 on 2023-11-19 11:21

import mainpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0043_enrollment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('text', models.TextField()),
                ('review_for', models.CharField(blank=True, choices=[(mainpage.models.EnrollmentType['BASE'], mainpage.models.EnrollmentType['BASE']), (mainpage.models.EnrollmentType['ADVANCED'], mainpage.models.EnrollmentType['ADVANCED'])], max_length=10, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=254, null=True)),
                ('reviewed_at', models.DateField()),
            ],
        ),
    ]
