# Generated by Django 2.0.5 on 2018-11-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='ID заказа')),
                ('event_id', models.IntegerField(verbose_name='ID мероприятия')),
                ('status', models.CharField(choices=[('n', 'новый'), ('p', 'оплачено'), ('c', 'отказ'), ('1', 'напоминание 1'), ('2', 'напоминание 2'), ('3', 'напоминание 3')], default='n', max_length=1, verbose_name='статус')),
                ('reg_date', models.DateTimeField(verbose_name='дата заказа')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('surname', models.CharField(max_length=32, verbose_name='фамилия')),
                ('printed_id', models.CharField(max_length=20, verbose_name='ID печатный')),
            ],
            options={
                'verbose_name': 'билет',
                'verbose_name_plural': 'билеты',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order_id', 'event_id'], name='unique_ticket_index'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'reg_date'], name='expiration_ticket_index'),
        ),
    ]
