# Generated by Django 2.0.5 on 2018-11-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepad_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(default='Learn Python 11', max_length=32, verbose_name='событие'),
            preserve_default=False,
        ),
    ]
